# Generated by Django 6.0.4 on 2026-06-09 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('cantitate_stoc', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unitate_masura', models.CharField(help_text='ex: g, ml, buc', max_length=20)),
                ('prag_alerta', models.DecimalField(decimal_places=2, default=10.0, help_text='Notifică când stocul scade sub această valoare', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Masa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_masa', models.IntegerField(unique=True)),
                ('token_qr', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='comanda',
            name='urgenta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produs',
            name='tip_produs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='IngredientReteta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitate_necesara', models.DecimalField(decimal_places=2, help_text='Cantitatea necesară pentru o porție', max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredient')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente_reteta', to='core.produs')),
            ],
        ),
        migrations.AddField(
            model_name='comanda',
            name='masa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.masa'),
        ),
        migrations.CreateModel(
            name='ProfilStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_angajat', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('ospatar', 'Ospătar'), ('bucatar', 'Bucătar'), ('admin', 'Admin')], default='ospatar', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
