# Generated by Django 6.0.4 on 2026-06-09 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produs',
            name='tip_produs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ProfilStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_angajat', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('ospatar', 'Ospătar'), ('bucatar', 'Bucătar'), ('admin', 'Admin')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
