# Generated by Django 6.0.6 on 2026-06-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ingredient_masa_comanda_urgenta_produs_tip_produs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produs',
            name='timp_preparare_min',
            field=models.PositiveIntegerField(default=15, help_text='Timp estimat de preparare în minute'),
        ),
    ]
